#!/usr/bin/env bash
set -euo pipefail

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$HOME/.local/bin"
export PYTHONUNBUFFERED=1
: "${BRAINLAYER_BACKUP_CLIENT_TIMEOUT_SECONDS:=0}"
export BRAINLAYER_BACKUP_CLIENT_TIMEOUT_SECONDS
: "${BRAINLAYER_BACKUP_TIMEOUT_SECONDS:=7200}"
export BRAINLAYER_BACKUP_TIMEOUT_SECONDS
: "${BRAINLAYER_BACKUP_ATTEMPT_MAX_AGE_SECONDS:=86400}"
export BRAINLAYER_BACKUP_ATTEMPT_MAX_AGE_SECONDS
: "${BRAINLAYER_BACKUP_LOG_PROVENANCE:=real}"
export BRAINLAYER_BACKUP_LOG_PROVENANCE
BRAINLAYER_DIR="${BRAINLAYER_DIR:-__BRAINLAYER_DIR_VALUE__}"
case "$BRAINLAYER_DIR" in
    __BRAINLAYER_DIR_*) BRAINLAYER_DIR="$HOME/Gits/brainlayer" ;;
esac
export PYTHONPATH="$BRAINLAYER_DIR/src${PYTHONPATH:+:$PYTHONPATH}"

exec "${BRAINLAYER_PYTHON:-python3}" -m brainlayer.backup_daily
