#!/usr/bin/env bash
set -euo pipefail

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$HOME/.local/bin"
export PYTHONUNBUFFERED=1
: "${BRAINLAYER_BACKUP_CLIENT_TIMEOUT_SECONDS:=0}"
export BRAINLAYER_BACKUP_CLIENT_TIMEOUT_SECONDS
: "${BRAINLAYER_BACKUP_TIMEOUT_SECONDS:=28800}"
export BRAINLAYER_BACKUP_TIMEOUT_SECONDS
: "${BRAINLAYER_BACKUP_SQLITE_CHECK_TIMEOUT_SECONDS:=0}"
export BRAINLAYER_BACKUP_SQLITE_CHECK_TIMEOUT_SECONDS
: "${BRAINLAYER_BACKUP_ATTEMPT_MAX_AGE_SECONDS:=86400}"
export BRAINLAYER_BACKUP_ATTEMPT_MAX_AGE_SECONDS
: "${BRAINLAYER_BACKUP_LOG_PROVENANCE:=real}"
export BRAINLAYER_BACKUP_LOG_PROVENANCE
unset PYTHONPATH

: "${BRAINLAYER_PYTHON:?installer must render the prefix-aware keg interpreter}"
exec "$BRAINLAYER_PYTHON" -m brainlayer.backup_daily
