"""Interactive setup wizard for BrainLayer.

Detects the user's environment, recommends configuration,
and guides through first-time setup.
"""

import platform
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


@dataclass
class WizardConfig:
    """Configuration generated by the wizard."""

    enrich_backend: str = "none"
    extras: list[str] = field(default_factory=list)
    claude_projects_dir: Optional[Path] = None
    db_path: Optional[Path] = None


def detect_environment() -> dict:
    """Detect available tools and data sources."""
    env = {}

    # Check Ollama
    env["ollama_available"] = shutil.which("ollama") is not None
    if env["ollama_available"]:
        try:
            result = subprocess.run(["ollama", "list"], capture_output=True, text=True, timeout=5)
            env["ollama_models"] = result.stdout.strip().split("\n") if result.returncode == 0 else []
        except (subprocess.TimeoutExpired, FileNotFoundError):
            env["ollama_available"] = False
            env["ollama_models"] = []
    else:
        env["ollama_models"] = []

    # Check Apple Silicon (for MLX)
    env["is_apple_silicon"] = platform.system() == "Darwin" and platform.machine() == "arm64"

    # Check Claude Code conversations
    claude_dir = Path.home() / ".claude" / "projects"
    env["claude_projects_dir"] = claude_dir if claude_dir.exists() else None
    env["conversation_count"] = len(list(claude_dir.rglob("*.jsonl"))) if claude_dir.exists() else 0

    # Check for WhatsApp exports
    env["whatsapp_available"] = False

    # Check for existing DB
    default_db = Path.home() / ".local" / "share" / "brainlayer" / "brainlayer.db"
    env["existing_db"] = default_db.exists()

    return env


def run_wizard() -> WizardConfig:
    """Run the interactive setup wizard. Returns configuration."""
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Confirm, Prompt

    console = Console()
    config = WizardConfig()

    console.print(
        Panel.fit(
            "[bold]BrainLayer Setup Wizard[/bold]\nLike git for your AI conversations.",
            border_style="blue",
        )
    )

    console.print("\n[dim]Detecting your environment...[/dim]")
    env = detect_environment()

    console.print(f"\n  Claude Code conversations: [green]{env['conversation_count']}[/green] JSONL files")
    console.print(
        f"  Ollama: {'[green]available[/green]' if env['ollama_available'] else '[yellow]not found[/yellow]'}"
    )
    console.print(f"  Apple Silicon (MLX): {'[green]yes[/green]' if env['is_apple_silicon'] else '[dim]no[/dim]'}")
    console.print(f"  Existing DB: {'[green]found[/green]' if env['existing_db'] else '[dim]none[/dim]'}")

    if env["is_apple_silicon"] and env["ollama_available"]:
        backend = Prompt.ask(
            "\nEnrichment backend",
            choices=["ollama", "mlx", "none"],
            default="ollama",
        )
    elif env["ollama_available"]:
        backend = Prompt.ask(
            "\nEnrichment backend",
            choices=["ollama", "none"],
            default="ollama",
        )
    else:
        console.print("\n[yellow]No local LLM found. Enrichment disabled.[/yellow]")
        console.print("[dim]Install Ollama (ollama.ai) for local enrichment.[/dim]")
        backend = "none"
    config.enrich_backend = backend

    extras = []
    if Confirm.ask("\nInstall style analysis (communication patterns)?", default=False):
        extras.append("style")
    if Confirm.ask("Install YouTube transcript indexing?", default=False):
        extras.append("youtube")
    if Confirm.ask("Install Obsidian export?", default=False):
        extras.append("obsidian")
    config.extras = extras

    if env["claude_projects_dir"]:
        config.claude_projects_dir = env["claude_projects_dir"]
    else:
        custom = Prompt.ask(
            "Path to Claude Code projects directory",
            default=str(Path.home() / ".claude" / "projects"),
        )
        config.claude_projects_dir = Path(custom)

    console.print(
        Panel.fit(
            f"[bold green]Setup complete![/bold green]\n\n"
            f"  Backend: {config.enrich_backend}\n"
            f"  Extras: {', '.join(config.extras) or 'none'}\n"
            f"  Source: {config.claude_projects_dir}\n\n"
            f"Run [bold]brainlayer index[/bold] to index your conversations.",
            border_style="green",
        )
    )

    return config
