#!/usr/bin/env python3
"""Generate ~/.config/brainlayer/scopes.yaml from git repos in ~/Gits/.

Scans for git repositories and maps their paths to project names.
Run once to bootstrap, then edit manually as needed.

Usage:
    python3 scripts/scope-config.py
    python3 scripts/scope-config.py --gits-dir ~/projects
    python3 scripts/scope-config.py --dry-run
"""

import argparse
import os
import subprocess
from pathlib import Path


def find_git_repos(gits_dir: Path) -> list[tuple[Path, str]]:
    """Find git repositories and extract project names."""
    repos = []
    if not gits_dir.exists():
        return repos

    for entry in sorted(gits_dir.iterdir()):
        if not entry.is_dir():
            continue
        git_dir = entry / ".git"
        if not git_dir.exists():
            continue

        # Use directory name as project name
        project_name = entry.name
        repos.append((entry, project_name))

    return repos


def generate_scopes_yaml(repos: list[tuple[Path, str]], default: str = "all") -> str:
    """Generate scopes.yaml content."""
    lines = [
        "# BrainLayer project scoping config",
        "# Maps directory prefixes to project names for auto-scoping brain_search",
        "# Generated by: python3 scripts/scope-config.py",
        "#",
        "# brain_search auto-scopes to the matched project when 'project' param is None.",
        "# Use project='all' to search all projects explicitly.",
        "",
        "scopes:",
    ]

    for path, name in repos:
        # Use ~ shorthand for home directory
        display_path = str(path).replace(str(Path.home()), "~")
        lines.append(f'  {display_path}: "{name}"')

    lines.append("")
    lines.append(f'default: "{default}"')
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate BrainLayer scopes.yaml")
    parser.add_argument(
        "--gits-dir",
        type=Path,
        default=Path.home() / "Gits",
        help="Directory containing git repos (default: ~/Gits)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path.home() / ".config" / "brainlayer" / "scopes.yaml",
        help="Output path (default: ~/.config/brainlayer/scopes.yaml)",
    )
    parser.add_argument("--default", default="all", help="Default scope when no match (default: all)")
    parser.add_argument("--dry-run", action="store_true", help="Print to stdout instead of writing")
    args = parser.parse_args()

    repos = find_git_repos(args.gits_dir)

    if not repos:
        print(f"No git repos found in {args.gits_dir}")
        return

    content = generate_scopes_yaml(repos, default=args.default)

    if args.dry_run:
        print(content)
        print(f"\n# Found {len(repos)} repos in {args.gits_dir}")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(content)
        print(f"Wrote {args.output} ({len(repos)} repos)")


if __name__ == "__main__":
    main()
